### PR TITLE
Bandwidth Usage Charts

### PR DESCRIPTION
**Pull request by notlesh**

### CODE REVIEW

**Comment by notlesh** [comment]
This needs aesthetic tweaks, but it's functionally working at this point. I'll address tweaks in another PR.

**Comment by despair86** [comment]
doesn't this make lokicp GPL3 only?

**Comment by majestrate** [comment]
yes that's and that's probably fine

**Comment by notlesh** [comment]
> doesn't this make lokicp GPL3 only?

Why would it do that? Rather, what is `this`?

**Comment by despair86** [comment]
qt charts is closed source OR GPL3 exclusive

**Pull request merged**
