### PR TITLE
About Lokinet

### PR DESCRIPTION
**Pull request by neuroscr**
- moves exit option to the very bottom (this would be what's expected for a macos systray app)
- puts "about" menu item right above it
- add link color to style
- include #6 (forgive me)
- haven't tested on non-mac platforms
- in draft because it's awaiting input/approval from Kee

Screen Shot 2020-01-09 at 11 21 49 PM

### CODE REVIEW

**Comment by KeeJef** [comment]
Can we please change the Logo to not be grey on black

**Comment by KeeJef** [comment]
Also no need for the copyright statement

**Comment by neuroscr** [comment]
I could turn the windows background white but then it doesn’t match our theme. Otherwise I’ll ping you about other logo options.

Can remove the copyright line but I think we could link to loki.network somewhere in the about (just for marketing reasons)

**Comment by neuroscr** [comment]
Screen Shot 2020-04-20 at 3 02 05 PM

**Comment by notlesh** [comment]
It looks like commits a8878ff and fff53b9 are pulling in unrelated stuff and then undoing it. Can we clean this up (e.g. rebase, cherry-pick, etc.) and clean up the history?

**Comment by jagerman** [comment]
Probably just needs to be squashed into one.

**Pull request closed without merging**
